# Generated by Django 6.0 on 2025-12-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='記録名')),
                ('description', models.TextField(verbose_name='記録内容')),
                ('observed_at', models.DateTimeField(verbose_name='発生日時')),
                ('anomaly_level', models.IntegerField(choices=[(1, '違和感'), (2, '軽度異常'), (3, '注意'), (4, '重大'), (5, '未分類')], default=1, verbose_name='異常レベル')),
                ('note', models.TextField(blank=True, verbose_name='備考（記録員メモ）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
