# Generated by Django 6.0 on 2025-12-25 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerJudgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgement', models.IntegerField(choices=[(1, '問題なし'), (2, '要注意'), (3, '再調査が必要')], verbose_name='判断')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgements', to='records.anomalyrecord')),
            ],
        ),
    ]
