# Generated by Django 6.0 on 2026-01-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_playerjudgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalyrecord',
            name='comment_high',
            field=models.TextField(blank=True, help_text='公式レベルより高く評価された際に表示される分析コメント', verbose_name='所見（高く判定した場合）'),
        ),
        migrations.AddField(
            model_name='anomalyrecord',
            name='comment_low',
            field=models.TextField(blank=True, help_text='公式レベルより低く評価された際に表示される分析コメント', verbose_name='所見（低く判定した場合）'),
        ),
        migrations.AlterField(
            model_name='anomalyrecord',
            name='anomaly_level',
            field=models.IntegerField(choices=[(1, '違和感'), (2, '軽度異常'), (3, '注意'), (4, '重大'), (5, '未分類')], default=1, verbose_name='公式異常レベル'),
        ),
    ]
